const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.video,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.sliderbar,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pathfinding,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.Mainmenu_Event6_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.PlatformInfo.Exps.FramesPerSecond,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.ScriptsInEvents.Main_Event50_Act1,
		C3.Plugins.Text.Acts.SetPos,
		C3.ScriptsInEvents.Main_Event52_Act1,
		C3.ScriptsInEvents.Main_Event54_Act5,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Background: 0},
	{TitleLogo: 0},
	{SettingsButton: 0},
	{Sprite3: 0},
	{Intro_1: 0},
	{Intro_2: 0},
	{Mouse: 0},
	{Back: 0},
	{start: 0},
	{quit: 0},
	{PlatformInfo: 0},
	{Sound: 0},
	{Control: 0},
	{Sprite: 0},
	{Bgm: 0},
	{Unmute: 0},
	{bgmtext: 0},
	{Text: 0},
	{BgmController: 0},
	{BGM_Controller: 0},
	{SFXController: 0},
	{SFX_Controller: 0},
	{Health: 0},
	{Hunger: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{AsepPlayer: 0},
	{Keyboard: 0},
	{Mute: 0},
	{TextInput: 0},
	{Text2: 0},
	{Text3: 0},
	{GrassIsSpawned: 0},
	{Grass: 0},
	{ScrollTo: 0},
	{Cam: 0},
	{Coordinate: 0},
	{MuteUnmute_Controller: 0},
	{Sprite2: 0},
	{Grass1: 0},
	{Grass2: 0},
	{Grass3: 0},
	{Grass4: 0},
	{Grass5: 0},
	{Grass6: 0},
	{Grass7: 0},
	{Grass8: 0},
	{Grass9: 0},
	{Grass10: 0},
	{Grass11: 0},
	{Grass12: 0},
	{Toolbar: 0},
	{FPS_TEXT: 0},
	{Zombie_Health: 0},
	{Bullet: 0},
	{Pathfinding: 0},
	{Zombie: 0},
	{Cow_Health: 0},
	{Cow: 0},
	{Sprite4: 0},
	{Health_Text: 0},
	{HitBox: 0},
	{TiledBackground: 0},
	{Pause_Text: 0},
	{Sprite5: 0},
	{Nas: 0},
	{Pause_Button: 0},
	{Continue_Text: 0},
	{Main_Menu: 0},
	{Pause_Button2: 0},
	{Hunger_Text: 0},
	{Death_Text: 0},
	{Button_died: 0},
	{qUIT_tEXT: 0},
	{Ground_1: 0},
	{Hearts: 0},
	{F3_DEBUG: 0},
	{Delta_Time: 0},
	{Pause: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	TitleLogo: class extends self.ITiledBackgroundInstance {},
	SettingsButton: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Intro_1: class extends self.IWorldInstance {},
	Intro_2: class extends self.IWorldInstance {},
	Mouse: class extends self.IInstance {},
	Back: class extends self.ITiledBackgroundInstance {},
	start: class extends self.ITextInstance {},
	quit: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sound: class extends self.ITextInstance {},
	Control: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Bgm: class extends self.IInstance {},
	Unmute: class extends self.ISpriteInstance {},
	bgmtext: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	BGM_Controller: class extends self.ISliderBarInstance {},
	SFX_Controller: class extends self.ISliderBarInstance {},
	AsepPlayer: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mute: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Grass: class extends self.ITiledBackgroundInstance {},
	Cam: class extends self.ISpriteInstance {},
	Coordinate: class extends self.ITextInstance {},
	MuteUnmute_Controller: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Grass1: class extends self.ISpriteInstance {},
	Grass2: class extends self.ISpriteInstance {},
	Grass3: class extends self.ISpriteInstance {},
	Grass4: class extends self.ISpriteInstance {},
	Grass5: class extends self.ISpriteInstance {},
	Grass6: class extends self.ISpriteInstance {},
	Grass7: class extends self.ISpriteInstance {},
	Grass8: class extends self.ISpriteInstance {},
	Grass9: class extends self.ISpriteInstance {},
	Grass10: class extends self.ISpriteInstance {},
	Grass11: class extends self.ISpriteInstance {},
	Grass12: class extends self.ISpriteInstance {},
	Toolbar: class extends self.ISpriteInstance {},
	FPS_TEXT: class extends self.ITextInstance {},
	Zombie: class extends self.ISpriteInstance {},
	Cow: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Health: class extends self.ISpriteInstance {},
	Health_Text: class extends self.ITextInstance {},
	HitBox: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Pause_Text: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Nas: class extends self.ISpriteInstance {},
	Pause_Button: class extends self.ISpriteInstance {},
	Continue_Text: class extends self.ITextInstance {},
	Main_Menu: class extends self.ITextInstance {},
	Pause_Button2: class extends self.ISpriteInstance {},
	Hunger_Text: class extends self.ITextInstance {},
	Death_Text: class extends self.ITextInstance {},
	Button_died: class extends self.ISpriteInstance {},
	qUIT_tEXT: class extends self.ITextInstance {}
}